cargo-features = ["edition2024"]

[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = "0.10.1"
clap = { version = "4.5.39", features = ["derive"] }
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
